version: '3.8'

services:
  github-runner-kitdigital:
    image: github-runner-kitdigital
    build:
      context: .
    container_name: github-runner-kitdigital
    restart: unless-stopped
    environment:
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
      GH_TOKEN: ${GH_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      WORK_DIRECTORY: ${WORK_DIRECTORY}
      LABELS: ${LABELS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
